import { useState, useEffect } from 'react';
import {
  BarChart3,
  Loader2,
  Sparkles,
  AlertCircle,
  Clock,
  RefreshCw,
} from 'lucide-react';
import { generateInsights, getCachedInsights, getOperationsSummary } from '../services/api';
import type { InsightsResponse } from '../types/insights';
import type { OperationSummary } from '../types';
import InsightsScopeSelector from './InsightsScopeSelector';
import StatsCards from './StatsCards';
import GeneralInsightsTab from './GeneralInsightsTab';
import ExpertAnalysisTab from './ExpertAnalysisTab';

function Insights() {
  const [activeTab, setActiveTab] = useState<'general' | 'expert'>('general');
  const [loading, setLoading] = useState(false);
  const [loadingOperations, setLoadingOperations] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [insights, setInsights] = useState<InsightsResponse | null>(null);
  const [operations, setOperations] = useState<OperationSummary[]>([]);
  const [selectedOperations, setSelectedOperations] = useState<string[]>([]);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    loadOperations();
  }, []);

  // Auto-load cached insights when operations are loaded or selected operations change
  useEffect(() => {
    if (operations.length > 0 && selectedOperations.length > 0 && !loading) {
      loadCachedInsights();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [operations.length, selectedOperations.join(',')]);

  const loadOperations = async () => {
    setLoadingOperations(true);
    try {
      const ops = await getOperationsSummary();
      setOperations(ops);
      // Auto-select all operations by default
      if (ops.length > 0) {
        setSelectedOperations(ops.map((op) => op.id));
      }
    } catch (err: any) {
      console.error('Failed to load operations:', err);
      setError(err.response?.data?.detail || err.message || 'Failed to load operations');
    } finally {
      setLoadingOperations(false);
    }
  };

  const loadCachedInsights = async () => {
    if (selectedOperations.length === 0) {
      return;
    }

    try {
      const cached = await getCachedInsights(selectedOperations);
      if (cached) {
        console.log('Loaded cached insights');
        setInsights(cached);
        setHasAutoGenerated(false); // Reset flag when cache is found
      } else {
        // No cache exists - automatically generate insights in the background (only once per mount)
        if (!hasAutoGenerated && !loading) {
          console.log('No cached insights found, generating in background...');
          setHasAutoGenerated(true);
          handleGenerateInsights(false);
        }
      }
    } catch (err: any) {
      // Silently fail - no cache is fine, but try to generate (only once per mount)
      if (!hasAutoGenerated && !loading) {
        console.log('No cached insights available, generating in background...');
        setHasAutoGenerated(true);
        handleGenerateInsights(false);
      }
    }
  };

  const handleGenerateInsights = async (forceRefresh: boolean = false) => {
    if (selectedOperations.length === 0) {
      setError('Please select at least one operation');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const result = await generateInsights(selectedOperations, forceRefresh);
      setInsights(result);
    } catch (err: any) {
      console.error('Failed to generate insights:', err);
      setError(
        err.response?.data?.detail || err.message || 'Failed to generate insights'
      );
    } finally {
      setLoading(false);
    }
  };

  const totalSessions = operations.reduce((sum, op) => sum + op.session_count, 0);
  const selectedSessions = operations
    .filter((op) => selectedOperations.includes(op.id))
    .reduce((sum, op) => sum + op.session_count, 0);

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold text-white flex items-center">
          <BarChart3 className="h-8 w-8 mr-3" />
          Insights
        </h1>
        <div className="flex items-center gap-2">
          {insights && (
            <button
              onClick={() => handleGenerateInsights(true)}
              disabled={loading || selectedOperations.length === 0 || loadingOperations}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Re-analyzing...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4" />
                  Re-analyze
                </>
              )}
            </button>
          )}
          <button
            onClick={() => handleGenerateInsights(false)}
            disabled={loading || selectedOperations.length === 0 || loadingOperations}
            className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate Insights
              </>
            )}
          </button>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="flex gap-6">
        {/* Left column - Content (wider) */}
        <div className="flex-1 min-w-0">
          {/* Error Display */}
          {error && (
            <div className="mb-6 p-4 bg-red-900/50 border border-red-700 rounded-md text-red-200 flex items-center gap-2">
              <AlertCircle className="h-5 w-5 flex-shrink-0" />
              <span>{error}</span>
              <button
                onClick={() => setError(null)}
                className="ml-auto text-red-300 hover:text-red-100"
              >
                ×
              </button>
            </div>
          )}

          {/* Loading State */}
          {loading && (
            <div className="bg-gray-800 border border-gray-700 rounded-lg p-12 mb-6">
              <div className="flex flex-col items-center justify-center">
                <Loader2 className="h-12 w-12 text-blue-400 animate-spin mb-4" />
                <p className="text-gray-300 text-lg mb-2">Analyzing sessions...</p>
                <p className="text-gray-500 text-sm">
                  Analyzing {selectedSessions} session{selectedSessions !== 1 ? 's' : ''}{' '}
                  across {selectedOperations.length} operation
                  {selectedOperations.length !== 1 ? 's' : ''}...
                </p>
              </div>
            </div>
          )}

          {/* Empty State - No Insights Generated */}
          {!loading && !insights && !error && (
            <div className="bg-gray-800 border border-gray-700 rounded-lg p-12 mb-6">
              <div className="flex flex-col items-center justify-center text-center">
                <BarChart3 className="h-16 w-16 text-gray-500 mb-4 opacity-50" />
                <h3 className="text-xl font-semibold text-white mb-2">
                  No Insights Generated Yet
                </h3>
                <p className="text-gray-400 mb-6 max-w-md">
                  Select operations and click "Generate Insights" to see analysis of your red
                  team operations.
                </p>
                {selectedOperations.length === 0 && (
                  <p className="text-yellow-400 text-sm">
                    Please select at least one operation to generate insights.
                  </p>
                )}
              </div>
            </div>
          )}

          {/* Insights Content */}
          {!loading && insights && (
            <div className="space-y-6 animate-fade-in">
              {/* Last Updated */}
              <div className="flex items-center justify-between bg-gray-800/50 border border-gray-700 rounded-md px-4 py-2">
                <div className="flex items-center gap-2 text-sm text-gray-400">
                  <Clock className="h-4 w-4" />
                  <span>
                    Last updated: {new Date(insights.generated_at).toLocaleString()}
                  </span>
                </div>
                <button
                  onClick={() => handleGenerateInsights(true)}
                  disabled={loading}
                  className="text-sm px-3 py-1 text-blue-400 hover:text-blue-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1"
                >
                  <RefreshCw className="h-3 w-3" />
                  Refresh
                </button>
              </div>

              {/* Stats Cards */}
              <StatsCards
                totalSessions={insights.general_insights.total_sessions}
                totalTargets={insights.general_insights.total_targets}
                totalFindings={insights.general_insights.total_findings}
                totalTools={insights.general_insights.total_tools}
              />

              {/* Tabs */}
              <div className="bg-gray-800 border border-gray-700 rounded-lg">
                <div className="flex border-b border-gray-700">
                  <button
                    onClick={() => setActiveTab('general')}
                    className={`flex-1 px-6 py-4 text-sm font-medium transition-colors ${
                      activeTab === 'general'
                        ? 'text-white border-b-2 border-blue-500 bg-gray-800'
                        : 'text-gray-400 hover:text-gray-300 hover:bg-gray-800/50'
                    }`}
                  >
                    General Insights
                  </button>
                  <button
                    onClick={() => setActiveTab('expert')}
                    className={`flex-1 px-6 py-4 text-sm font-medium transition-colors ${
                      activeTab === 'expert'
                        ? 'text-white border-b-2 border-blue-500 bg-gray-800'
                        : 'text-gray-400 hover:text-gray-300 hover:bg-gray-800/50'
                    }`}
                  >
                    Expert Analysis
                  </button>
                </div>

                <div className="p-6">
                  {activeTab === 'general' ? (
                    <GeneralInsightsTab insights={insights.general_insights} />
                  ) : (
                    <ExpertAnalysisTab analysis={insights.expert_analysis} />
                  )}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Right column - Scope selector sidebar (300px, sticky) */}
        <div className="w-[300px] flex-shrink-0">
          <div className="sticky top-6 bg-gray-800 border border-gray-700 rounded-lg p-4 h-[calc(100vh-8rem)]">
            <InsightsScopeSelector
              operations={operations}
              selectedOperations={selectedOperations}
              onChange={setSelectedOperations}
              totalSessions={totalSessions}
              loading={loadingOperations}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Insights;

